"""create outbox table

Revision ID: cb2699335d57
Revises: 001
Create Date: 2026-04-21 13:35:21.970992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb2699335d57'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_job_id'), 'outbox', ['job_id'], unique=False)
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_index('ix_outbox_status_created_at', 'outbox', ['status', 'created_at'], unique=False)
    op.add_column('download_jobs', sa.Column('retry_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('download_jobs', sa.Column('max_retries', sa.Integer(), nullable=False, server_default=sa.text('3')))
    op.add_column('download_jobs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('download_jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # Drop FK constraint BEFORE altering either column type.
    # PostgreSQL forbids altering a column's type while it participates
    # in a foreign key (either as the referencing or referenced column).
    op.drop_constraint(op.f('download_jobs_user_id_fkey'), 'download_jobs', type_='foreignkey')

    # Alter download_jobs primary key (no FK dependencies)
    op.alter_column('download_jobs', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using='id::uuid',
               existing_nullable=False)
    op.alter_column('download_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('download_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_download_jobs_status'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_user_id'), table_name='download_jobs')
    op.create_index(op.f('ix_download_jobs_expires_at'), 'download_jobs', ['expires_at'], unique=False)

    # Alter users.id to UUID (FK already dropped)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using='id::uuid',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # Create partial unique index for active users only (soft-delete compatible)
    # This allows soft-deleted accounts to be reused while enforcing uniqueness for active accounts
    op.create_index('ix_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)

    # Alter download_jobs.user_id to UUID (users.id is now UUID)
    op.alter_column('download_jobs', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using='user_id::uuid',
               existing_nullable=False)
    # Use NO ACTION instead of CASCADE to support soft-delete (user.deleted_at is set, not physically deleted)
    # The partial unique index ix_users_email_active enforces email uniqueness only for active users
    op.create_foreign_key('fk_download_jobs_user_id', 'download_jobs', 'users', ['user_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_job_id'), table_name='outbox')
    op.drop_index('ix_outbox_status_created_at', table_name='outbox')
    op.drop_table('outbox')

    # Drop FK first so we can freely revert column types
    op.drop_constraint('fk_download_jobs_user_id', 'download_jobs', type_='foreignkey')

    # Revert users.id to VARCHAR before download_jobs.user_id so the
    # old FK (recreated later) has matching VARCHAR types on both sides.
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               postgresql_using='id::text',
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'deleted_at')

    # Now revert download_jobs columns (users.id is VARCHAR again)
    op.alter_column('download_jobs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               postgresql_using='user_id::text',
               existing_nullable=False)
    op.alter_column('download_jobs', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               postgresql_using='id::text',
               existing_nullable=False)
    op.alter_column('download_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('download_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_download_jobs_expires_at'), table_name='download_jobs')
    op.create_index(op.f('ix_download_jobs_status'), 'download_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_download_jobs_user_id'), 'download_jobs', ['user_id'], unique=False)
    # Recreate original FK now that both sides are VARCHAR again
    op.create_foreign_key(op.f('download_jobs_user_id_fkey'), 'download_jobs', 'users', ['user_id'], ['id'])
    op.drop_column('download_jobs', 'updated_at')
    op.drop_column('download_jobs', 'next_retry_at')
    op.drop_column('download_jobs', 'max_retries')
    op.drop_column('download_jobs', 'retry_count')
    # ### end Alembic commands ###
